const ACTION_TYPES = {
  GET_INTRO_INFO: 'GET_INTRO_INFO',
  GET_INTRO_INFO_LOADING: 'GET_INTRO_INFO_LOADING',
  GET_INTRO_INFO_SUCCESS: 'GET_INTRO_INFO_SUCCESS',
  GET_INTRO_INFO_ERROR: 'GET_INTRO_INFO_ERROR',

  GET_CLIENT_INFO: 'GET_CLIENT_INFO',
  GET_CLIENT_INFO_LOADING: 'GET_CLIENT_INFO_LOADING',
  GET_CLIENT_INFO_SUCCESS: 'GET_CLIENT_INFO_SUCCESS',
  GET_CLIENT_INFO_ERROR: 'GET_CLIENT_INFO_ERROR',

  GET_FEATURED_INFO: 'GET_FEATURED_INFO',
  GET_FEATURED_INFO_LOADING: 'GET_FEATURED_INFO_LOADING',
  GET_FEATURED_INFO_SUCCESS: 'GET_FEATURED_INFO_SUCCESS',
  GET_FEATURED_INFO_ERROR: 'GET_FEATURED_INFO_ERROR',
};

export default ACTION_TYPES;
